#!/bin/sh

uci -q get uqmi_sms.main >/dev/null || uci -q set uqmi_sms.main='uqmi_sms'
uci -q get uqmi_sms.main.device >/dev/null || uci -q set uqmi_sms.main.device='/dev/cdc-wdm0'
uci -q get uqmi_sms.main.storage >/dev/null || uci -q set uqmi_sms.main.storage='me'
uci -q commit uqmi_sms

exit 0
